global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'registration-application'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['registration-1:8080', 'registration-2:8080']
        labels:
          env: prod
          application: 'registration-service'
  - job_name: "localhost:8080"
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080']
        labels:
          env: dev
          application: 'registration-localhost-service'
