server:
  servlet:
    context-path: /api

spring:
  application:
    name: registration-dev
  datasource:
    url: jdbc:mariadb://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
        serialization-mode: via-dto
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:key/jwt-public.pub
          private-key-location: classpath:key/jwt-private.pem

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /docs/openapi3.yaml

jwt:
  secret-key: ${JWT_SECRET_KEY}

management:
  otlp:
    tracing:
      endpoint: "http://localhost:4318/v1/traces" # Tempo의 HTTP 수신 포트
  tracing:
    sampling:
      probability: 1.0 # 1.0은 모든 요청을 추적함 (개발용). 운영은 0.1(10%) 등으로 조절 권장.
  endpoints:
    web:
      exposure:
        include: "prometheus, health"

jdbc:
  datasource-proxy:
    include-parameter-values: true
    logging: slf4j
    multiline: true
    query:
      log-level: DEBUG
      logger-name: query-logger
      enable-logging: true
    slow-query:
      enable-logging: true
      log-level: WARN
      logger-name: slow-query-logger
      threshold: 2 # 2초이상걸리면 slow

logging:
  level:
    query-logger: DEBUG
    slow-query-logger: WARN
