server:
  servlet:
    context-path: /api

spring:
  application:
    name: registration-prod
  datasource:
    url: jdbc:mariadb://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:key/jwt-public.pub
          private-key-location: classpath:key/jwt-private.pem

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /docs/openapi3.yaml

management:
  otlp:
    tracing:
      endpoint: ${TEMPO_ENDPOINT} # Tempo의 HTTP 수신 포트
  tracing:
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: "prometheus, health"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true  # 이 부분이 있어야 histogram_quantile이 작동함

jwt:
  secret-key: ${JWT_SECRET_KEY}

jdbc:
  datasource-proxy:
    logging: slf4j
    multiline: false
    slow-query:
      enable-logging: true
      log-level: WARN
      logger-name: slow-query-logger
      threshold: 2 # 2초이상걸리면 slow

logging:
  level:
    slow-query-logger: WARN

loki:
  url: ${LOKI_URL}

